# Generated by Django 4.2.7 on 2026-09-29 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('movement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('purchase', 'Purchase Receipt'), ('sale', 'Sale'), ('return_in', 'Customer Return In'), ('return_out', 'Return Out to Supplier'), ('adjustment_in', 'Manual Adjustment In'), ('adjustment_out', 'Manual Adjustment Out'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('opening', 'Opening Balance')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['warehouse', 'product', 'created_at'], name='stock_movem_warehou_9e57a2_idx'), models.Index(fields=['reference_type', 'reference_id'], name='stock_movem_referen_a0d8b9_idx'), models.Index(fields=['movement_type'], name='stock_movem_movemen_d922c9_idx')],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('quantity_available', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('last_stocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_sold_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_records', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['warehouse', 'product'], name='inventory_warehou_d4bfbf_idx'), models.Index(fields=['product'], name='inventory_product_58b6bd_idx')],
                'unique_together': {('warehouse', 'product')},
            },
        ),
    ]
