# Generated by Django 4.2.7 on 2026-09-29 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('transfer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transfer_number', models.CharField(max_length=60, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_transit', 'In Transit'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='warehouses.warehouse')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transfers', to=settings.AUTH_USER_MODEL)),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'stock_transfers',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='StockTransferItem',
            fields=[
                ('transfer_item_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('received_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_items', to='products.product')),
                ('transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stocktransfer')),
            ],
            options={
                'db_table': 'stock_transfer_items',
                'unique_together': {('transfer', 'product')},
            },
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['status'], name='stock_trans_status_332e43_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['from_warehouse'], name='stock_trans_from_wa_14be90_idx'),
        ),
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['to_warehouse'], name='stock_trans_to_ware_fa3dc7_idx'),
        ),
    ]
