# Generated by Django 4.2.7 on 2026-09-29 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('warehouses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAlert',
            fields=[
                ('alert_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('low_stock', 'Low Stock'), ('stock_out', 'Stock Out'), ('overstock', 'Overstock'), ('unusual_demand', 'Unusual Demand')], db_index=True, max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], db_index=True, default='warning', max_length=20)),
                ('threshold_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'inventory_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'severity'], name='inventory_a_status_214d82_idx'), models.Index(fields=['product', 'warehouse'], name='inventory_a_product_969b50_idx')],
            },
        ),
    ]
