# Generated by Django 4.2.7 on 2026-10-02 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('setting_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('setting_key', models.CharField(max_length=120, unique=True)),
                ('setting_value', models.TextField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_settings',
                'ordering': ['setting_key'],
            },
        ),
    ]
