# Generated by Django 4.2.7 on 2026-09-29 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('forecast_run_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('run_name', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50, null=True)),
                ('forecast_horizon_days', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='queued', max_length=20)),
                ('training_start_date', models.DateField(blank=True, null=True)),
                ('training_end_date', models.DateField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecast_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'forecast_runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('recommendation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('current_stock', models.DecimalField(decimal_places=3, max_digits=14)),
                ('average_daily_demand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('lead_time_days', models.PositiveIntegerField(default=0)),
                ('safety_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reorder_point', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('suggested_order_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('converted', 'Converted'), ('dismissed', 'Dismissed')], db_index=True, default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='forecasting.forecastrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_recommendations', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_recommendations', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'reorder_recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('metric_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('metric_name', models.CharField(max_length=50)),
                ('metric_value', models.DecimalField(decimal_places=6, max_digits=14)),
                ('evaluation_start', models.DateField(blank=True, null=True)),
                ('evaluation_end', models.DateField(blank=True, null=True)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='forecasting.forecastrun')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'db_table': 'model_metrics',
                'indexes': [models.Index(fields=['forecast_run', 'metric_name'], name='model_metri_forecas_df49ef_idx')],
            },
        ),
        migrations.CreateModel(
            name='DemandHistoryDaily',
            fields=[
                ('demand_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('demand_date', models.DateField(db_index=True)),
                ('units_sold', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('units_returned', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('net_demand', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'demand_history_daily',
                'ordering': ['-demand_date'],
                'indexes': [models.Index(fields=['product', 'warehouse', 'demand_date'], name='demand_hist_product_bae7d6_idx'), models.Index(fields=['demand_date'], name='demand_hist_demand__07a4fe_idx')],
                'unique_together': {('product', 'warehouse', 'demand_date')},
            },
        ),
        migrations.CreateModel(
            name='DemandForecast',
            fields=[
                ('forecast_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('forecast_date', models.DateField()),
                ('predicted_demand', models.DecimalField(decimal_places=3, max_digits=14)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('forecast_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='forecasting.forecastrun')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='products.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecasts', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'demand_forecasts',
                'indexes': [models.Index(fields=['forecast_run', 'product', 'warehouse'], name='demand_fore_forecas_c65eb3_idx'), models.Index(fields=['forecast_date'], name='demand_fore_forecas_57a570_idx')],
            },
        ),
    ]
