# Generated by Django 4.2.7 on 2026-09-29 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('warehouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('warehouse_code', models.CharField(max_length=50, unique=True)),
                ('warehouse_name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('manager_name', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'warehouses',
                'ordering': ['warehouse_name'],
                'indexes': [models.Index(fields=['warehouse_code'], name='warehouses_warehou_fd3850_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserWarehouse',
            fields=[
                ('user_warehouse_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_assignments', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='warehouses.warehouse')),
            ],
            options={
                'db_table': 'user_warehouses',
                'ordering': ['-is_primary', 'warehouse__warehouse_name'],
                'unique_together': {('user', 'warehouse')},
            },
        ),
    ]
